import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CartProvider } from "../contexts/CartContext";
import { WishlistProvider } from "../context/WishlistContext";
import Navbar from "./components/Navbar"; // Adjust path based on folder structure
import Footer from "./components/Footer"; // Adjust path based on folder structure
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <WishlistProvider>
        <CartProvider>
        <Navbar />
        <main>{children}</main>
       <Footer />
       </CartProvider>
       </WishlistProvider>
      </body>
    </html>
  );
}